version: 2

models:
  
  - name: location
    # description: markdown string
    columns:
      - name: city_id
        description: "Chame primaria da tabela"
        tests:
          - unique
          - not_null
      - name: state_id
        tests:
          - not_null
      - name: country_id
        tests:
          - not_null
  
  - name: account_customers
    columns:
      - name: account_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: city_id
        tests:
          - not_null
          - relationships:
              to: ref('location')
              field: city_id
      - name: account_status
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'inactive']
      - name: customer_cpf
        tests:
          - unique
          - not_null